products:
  ahoy:
    name: Ahoy

  root:
    name: Root

languages:
  de-DE:
    name: Deutsch

  en-US:
    name: English

  es-ES:
    name: Español

  fr-FR:
    name: Français

  nl-NL:
    name: Nederlands

  pl-PL:
    name: Polski

  pt-BR:
    name: Português

  ru-RU:
    name: Russian
